import { Component, OnInit, Output, EventEmitter } from "@angular/core";

@Component({
  selector: "app-input-button-unit",
  template: `
    <input
      class="todo-input"
      #inputElementRef
      [value]="title"
      (keyup.enter)="submitValue($event.target.value)"
    />

    <button class="btn" (click)="submitValue(inputElementRef.value)">
      Save
    </button>
  `,
  styleUrls: ["./input-button-unit.component.css"]
})
export class InputButtonUnitComponent implements OnInit {
  title = "Type to-do list items here";

  @Output() submit: EventEmitter<string> = new EventEmitter();

  constructor() {
    this.changeTitle("My First Angular App");
  }

  ngOnInit() {}
  changeTitle(newTitle: string) {
    this.submit.emit(newTitle);
  }

  generateTitle(): string {
    return "This title was generated by a method.";
  }
  submitValue(newTitle: string) {
    this.submit.emit(newTitle);
  }
}
